### ISSUE TITLE
Для текстов использовать переводы через i18n

### ISSUE THREAD

**Issue by amshkv** [Hexlet/jsbrowser#17]
Сейчас текст встроена непосредственно в код, такие вещи хорошо делать через файлы переводов, чтобы была возможность поддерживать русский язык, например

**Comment by Guryanov-Maksim** [comment]
Добрый день! Добавил i18n в проект. Посмотрите, может быть можно закрыть issue?

**Comment by amshkv** [comment]
Ты прав, спасибо за участие, закрываю
