### ISSUE TITLE
добавить деплой на github pages

### ISSUE THREAD

**Issue by fey** [Hexlet/jsbrowser#26]

**Comment by kirillmarkeyev** [comment]
Здравствуйте!
Попробую взять в работу.

**Comment by kirillmarkeyev** [comment]
Сделал PR.

**Comment by EvSedov** [comment]
Не актуально, т.к. задача выполнена

**Comment by fey** [comment]
https://github.com/Hexlet/jsbrowser/pull/28
https://github.com/Hexlet/jsbrowser/pull/27
